### ISSUE TITLE
misleading names of temporary files

### ISSUE THREAD

**Issue by jwilk** [jwilk/scanhelper#1]
**Issue reported by @jsbien**:

The disk was full during a scanning session. There seem to be no way to restart processing after freeing the disk space and I was left with TIFF files named e.g p0316.png.tmp.scanhelper.

**Comment by jwilk** [comment]
(cc: @jsbien)

The good news is that in SANE ≥ 1.0.25, scanimage (which is what scanhelper uses under the hood) supports the PNG format natively.
My plan is to drop the use of temporary files completely, and instead require new enough SANE when using the PNG output format.

**Comment by jsbien** [comment]
It's OK with me.

**Comment by jwilk** [comment]
> SANE ≥ 1.0.25

To clarify, I meant sane-backends here. (sane-frontends in versioned independently.)
This version is available since Debian 9 (stretch, currently stable) and Ubuntu 16.04 (xenial).

**Comment by jwilk** [comment]
>My plan is to drop the use of temporary files completely, and instead require new enough SANE when using the PNG output format.

This was implemented in 4d69ee547dee4a64d3b177a225043b1ece6d2021.

**Comment by jwilk** [comment]
Fixed in scanhelper 0.7.
